version: '2'
services:
    app_uaa-mysql:
        container_name: app_uaa-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/app_uaa/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=app_uaa
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
